blueprint:
  name: Laundry Cycle Monitor
  description: >
    Monitor washer and dryer cycles using vibration sensors, send notifications when cycles are done,
    and persistently notify if wet laundry remains in the washer until the door is opened.
    
    **Note**: Please create the required `input_boolean` helpers (`input_boolean.washer_running` and `input_boolean.dryer_running`) manually before using this blueprint.
  domain: automation
  input:
    # Sensors
    washer_sensor:
      name: Washer Vibration Sensor
      description: Binary sensor that detects washer vibration.
      selector:
        entity:
          domain: binary_sensor
    dryer_sensor:
      name: Dryer Vibration Sensor
      description: Binary sensor that detects dryer vibration.
      selector:
        entity:
          domain: binary_sensor
    door_sensor:
      name: Washer Door Sensor
      description: Binary sensor that detects if the washer door is open.
      selector:
        entity:
          domain: binary_sensor

    # Helper Input Booleans
    washer_running_boolean:
      name: Washer Running Helper
      description: Input Boolean to track washer running state.
      selector:
        entity:
          domain: input_boolean
    dryer_running_boolean:
      name: Dryer Running Helper
      description: Input Boolean to track dryer running state.
      selector:
        entity:
          domain: input_boolean

    # Notification Settings
    notify_service:
      name: Notification Service
      description: >
        Enter the notification service (e.g., notify.mobile_app_yourphone).
      default: "notify.notify"
      selector:
        text:
    notify_target:
      name: Notification Target
      description: >
        Select the target for notifications (e.g., your mobile device).
      selector:
        target:
          # This selector allows selecting one or more entities or devices compatible with the notification service.
    notification_text_washer_done:
      name: Washer Done Notification Text
      description: Text to send when washer cycle is complete.
      default: "🧺 Washer cycle is complete."
      selector:
        text:
    notification_text_dryer_done:
      name: Dryer Done Notification Text
      description: Text to send when dryer cycle is complete.
      default: "🔄 Dryer cycle is complete."
      selector:
        text:
    notification_text_wet_laundry:
      name: Wet Laundry Notification Text
      description: Text to send when wet laundry is detected and door is not opened.
      default: "⚠️ There is wet laundry in the washer. Please transfer it to prevent mildew."
      selector:
        text:

    # Timing Settings
    washer_started_delay:
      name: Washer Started Delay
      description: Minutes the washer must be on to trigger "Washer Started".
      default: 4
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider
    washer_stopped_delay:
      name: Washer Stopped Delay
      description: Minutes the washer must be off to trigger "Washer Stopped".
      default: 10
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider
    dryer_started_delay:
      name: Dryer Started Delay
      description: Minutes the dryer must be on to trigger "Dryer Started".
      default: 4
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider
    dryer_stopped_delay:
      name: Dryer Stopped Delay
      description: Minutes the dryer must be off to trigger "Dryer Stopped".
      default: 10
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider

    # Notification Interval for Wet Laundry
    wet_laundry_notification_interval:
      name: Wet Laundry Notification Interval
      description: >
        Interval in minutes to send wet laundry notifications.
      default: 30
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: minutes
          mode: slider

trigger:
  - platform: state
    entity_id: !input washer_sensor
    to: 'on'
    for:
      minutes: !input washer_started_delay
    id: washer_started
  - platform: state
    entity_id: !input washer_sensor
    to: 'off'
    for:
      minutes: !input washer_stopped_delay
    id: washer_stopped
  - platform: state
    entity_id: !input dryer_sensor
    to: 'on'
    for:
      minutes: !input dryer_started_delay
    id: dryer_started
  - platform: state
    entity_id: !input dryer_sensor
    to: 'off'
    for:
      minutes: !input dryer_stopped_delay
    id: dryer_stopped
  - platform: time_pattern
    minutes: "/30"  # Fixed interval: every 30 minutes
    id: periodic_check

condition: []

action:
  - choose:
      # Handle Washer Started
      - conditions:
          - condition: trigger
            id: washer_started
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input washer_running_boolean

      # Handle Washer Stopped
      - conditions:
          - condition: trigger
            id: washer_stopped
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input washer_running_boolean
          - service: !input notify_service
            target: !input notify_target
            data:
              message: !input notification_text_washer_done

      # Handle Dryer Started
      - conditions:
          - condition: trigger
            id: dryer_started
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input dryer_running_boolean

      # Handle Dryer Stopped
      - conditions:
          - condition: trigger
            id: dryer_stopped
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input dryer_running_boolean
          - service: !input notify_service
            target: !input notify_target
            data:
              message: !input notification_text_dryer_done

      # Handle Periodic Wet Laundry Check
      - conditions:
          - condition: trigger
            id: periodic_check
        sequence:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input washer_running_boolean
                state: 'off'
              - condition: state
                entity_id: !input door_sensor
                state: 'off'
          - service: !input notify_service
            target: !input notify_target
            data:
              message: !input notification_text_wet_laundry

mode: parallel
