blueprint:
  name: Laundry Automation with Helper Creation
  description: Automation to monitor washer and dryer states, create input booleans if needed, and send notifications
  domain: automation
  input:
    washer_sensor:
      name: Washer Sensor
      description: Binary sensor for washer state
      selector:
        entity:
          domain: binary_sensor
    dryer_sensor:
      name: Dryer Sensor
      description: Binary sensor for dryer state
      selector:
        entity:
          domain: binary_sensor
    wet_laundry_sensor:
      name: Wet Laundry Sensor
      description: Sensor that detects wet laundry
      selector:
        entity:
          domain: binary_sensor
    washer_running_boolean:
      name: Washer Running Boolean
      description: Input Boolean to track washer running state
      selector:
        entity:
          domain: input_boolean
    dryer_running_boolean:
      name: Dryer Running Boolean
      description: Input Boolean to track dryer running state
      selector:
        entity:
          domain: input_boolean
    washer_started_minutes:
      name: Washer Started Minutes
      description: Minutes the washer must be on to trigger "Washer Started"
      default: 4
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider
    washer_stopped_minutes:
      name: Washer Stopped Minutes
      description: Minutes the washer must be off to trigger "Washer Stopped"
      default: 10
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider
    dryer_started_minutes:
      name: Dryer Started Minutes
      description: Minutes the dryer must be on to trigger "Dryer Started"
      default: 4
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider
    dryer_stopped_minutes:
      name: Dryer Stopped Minutes
      description: Minutes the dryer must be off to trigger "Dryer Stopped"
      default: 10
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes
          mode: slider

trigger:
  - platform: state
    entity_id: !input washer_sensor
    to: 'on'
    for:
      minutes: !input washer_started_minutes
  - platform: state
    entity_id: !input washer_sensor
    to: 'off'
    for:
      minutes: !input washer_stopped_minutes
  - platform: state
    entity_id: !input dryer_sensor
    to: 'on'
    for:
      minutes: !input dryer_started_minutes
  - platform: state
    entity_id: !input dryer_sensor
    to: 'off'
    for:
      minutes: !input dryer_stopped_minutes
  - platform: time_pattern
    minutes: "/30"

condition:
  - condition: state
    entity_id: !input wet_laundry_sensor
    state: 'on'
  - condition: state
    entity_id: !input washer_running_boolean
    state: 'off'

action:
  - choose:
      - conditions:
          - condition: trigger
            id: washer_started
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input washer_running_boolean
      - conditions:
          - condition: trigger
            id: washer_stopped
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input washer_running_boolean
          - event: laundry_event
            event_data:
              text: Washer is done
      - conditions:
          - condition: trigger
            id: dryer_started
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input dryer_running_boolean
      - conditions:
          - condition: trigger
            id: dryer_stopped
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input dryer_running_boolean
          - event: laundry_event
            event_data:
              text: Dryer is done
      - conditions:
          - condition: trigger
            id: wet_laundry_notification
        sequence:
          - event: laundry_event
            event_data:
              text: There is wet laundry in the washer
